apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: final-project
  template:
    metadata:
      labels:
        app: final-project
    spec:
      containers:
      - name: final-project
        image: shaluaugustine/final-project-devops-tcs:latest
        ports:
        - containerPort: 8080
