apiVersion: v1
kind: Service
metadata:
  name: final-project-service
spec:
  type: NodePort
  selector:
    app: final-project
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
